// Every default string a person reads, in one place. Mirrors the wording table on docs/journeys.html.
// Australian English. Never an em dash.
export const copy = {
  brand: "Bunting",
  landing: {
    title: "Event invites you text. RSVPs that sort themselves.",
    lede: "Make the invite, add your guests, and text each one a personal link from your own phone. They tap yes or no. You see who is coming.",
    google: "Continue with Google",
    signinError: "That sign-in did not go through. Please try again.",
  },
  app: {
    yourEvents: "Your events",
    newEvent: "New event",
    noEvents: "No events yet. Your first one takes about ten minutes.",
    signOut: "Sign out",
  },
  greeting: (name: string) => `Hi ${name}, something for you`,
  greetingGroup: "You're invited",
  rsvp: {
    heading: "RSVP",
    question: (name: string) => `Can ${name} make it?`,
    questionGroup: "Can you make it?",
    replyBy: (date: string) => `Please reply by ${date} so we can get the numbers right.`,
    yes: "Yes, we're coming",
    no: "Sorry, can't make it",
    yesQuiet: "I'll be there",
    noQuiet: "I can't be there, but I'm thinking of you",
    whoIsThis: "Who's this from?",
    yourName: "Your name",
    yourMobile: "Your mobile (optional, so we can text you the details)",
    continue: "Continue",
    change: "Change my answer",
    keep: "Keep it",
  },
  questions: {
    howMany: "How many of you?",
    children: "children",
    adults: "adults",
    names: "Who's coming?",
    namesHint: "First names are plenty. Everyone counts, little ones too.",
    dietary: "Anything we should know about food?",
    dietaryNote: "Allergies or anything else, in your words",
    access: "Any access needs?",
    accessHint: "Step-free entry, a quiet corner, anything that helps. Only if it helps us. Skip if not.",
    note: "A note for the host (optional)",
    emergencyName: "Emergency contact name",
    emergencyPhone: "Emergency contact mobile",
    send: "Send my reply",
    skip: "Skip the rest",
  },
  thanks: {
    yesTitle: "See you there!",
    yesBody: (count: number, host: string) =>
      count > 1 ? `We've got you down for ${count}. ${host} can't wait to see you.` : `We've got you down. ${host} can't wait to see you.`,
    noTitle: "Sorry you can't make it",
    noBody: (host: string) => `${host} will miss you. Thanks for letting us know.`,
    addToCalendar: "Add to calendar",
    google: "Google Calendar",
    apple: "Apple or Outlook",
    changed: "Reply updated",
  },
  sections: {
    details: "The details",
    day: "The day",
    afternoon: "The order of the afternoon",
    goodToKnow: "Good to know",
    plate: "Bring a plate",
    updates: "Updates",
    updatesBody: "Anything that changes shows here.",
    photos: "Photos",
    photosBody: "A photo for you after the party.",
    openInMaps: "Open in Maps",
    when: "When",
    where: "Where",
    wear: "Wear",
    questions: (host: string) => `Questions? Text ${host}`,
  },
  lines: {
    parentsStay: "Parents and family welcome to stay.",
    dropOff: "This is a drop-off party. We'll take good care of them.",
    siblingsWelcome: "Little brothers and sisters are welcome, just count them in your reply.",
    siblingsNo: "We're keeping it to invited kids only. Sorry, siblings!",
    giftsNone: "No gifts please, your company is the present.",
    giftsOptional: "Gifts are entirely optional.",
    photosKidsOff: "We'd love you to take photos, just please keep photos of the kids off social media. Thank you!",
    photosAsk: "Snap away, and please check with people before posting them online.",
    photosShare: "Take all the photos you like and share them with us after.",
    plateFree: "Bring something for the table if you feel inspired. No pressure at all.",
  },
  host: {
    coming: "coming",
    saidYes: "said yes",
    saidNo: "said no",
    noReply: "no reply",
    opened: "opened, not replied",
    addGuest: "Add a guest",
    name: "Name (as it appears on the invite, e.g. Oliver or The Nairs)",
    contactName: "Who you're texting (e.g. Priya), if different",
    phone: "Mobile",
    add: "Add",
    text: "Text",
    whatsapp: "WhatsApp",
    copy: "Copy link",
    copied: "Copied",
    sendNext: "Send next",
    allSent: "Everyone has been sent their link.",
    groupLink: "Group link for chats",
    groupLinkHint: "Anyone can open it. It asks their name, then gives them a personal link of their own.",
    remind: "Remind",
    newLink: "New link",
    trail: {
      added: "added",
      sent: "sent",
      opened: "opened",
      replied: "replied",
      reminded: "reminded",
    },
  },
  templates: {
    text: "Hi {name}! You're invited to {title}{date}. Everything is here, and you can reply with one tap: {link}",
    reminder: "Hi {name}, just checking you saw this one. {title}{date}. Can you make it? {link}",
    seeYouSoon: "See you tomorrow! {address}. Everything you need: {link}",
  },
  closed: {
    title: "This link is closed",
    body: "The host has closed the group link. Text them and they'll send you your own.",
  },
  notFound: {
    title: "That link doesn't look right",
    body: "Check the message it came in, or ask the host to send it again.",
  },
} as const;
