// Every default string a person reads, in one place. Mirrors the wording table on docs/journeys.html.
// Australian English. Never an em dash.
export const copy = {
  brand: "Bunting",
  landing: {
    title: "Event invites you text. RSVPs that sort themselves.",
    lede: "Make the invite, add your guests, and text each one a personal link from your own phone. They tap yes or no. You see who is coming.",
    google: "Continue with Google",
    signinError: "That sign-in did not go through. Please try again.",
  },
  app: {
    yourEvents: "Your events",
    newEvent: "New event",
    noEvents: "No events yet. Your first one takes about ten minutes.",
    signOut: "Sign out",
  },
  greeting: (name: string) => `Hi ${name}, something for you`,
  greetingGroup: "You're invited",
  envelope: {
    open: "Tap to open",
    // On the group link the envelope has no name to carry, so it is addressed to whoever opened it.
    toYou: "To you",
    eyebrowBirthday: "Trainer wanted",
  },
  rsvp: {
    heading: "RSVP",
    question: (name: string) => `Can ${name} make it?`,
    questionGroup: "Can you make it?",
    replyBy: (date: string) => `Please reply by ${date} so we can get the numbers right.`,
    yes: "Yes, we're coming",
    no: "Sorry, can't make it",
    yesQuiet: "I'll be there",
    noQuiet: "I can't be there, but I'm thinking of you",
    whoIsThis: "Who's this from?",
    yourName: "Your name",
    yourMobile: "Your mobile (optional, so we can text you the details)",
    continue: "Continue",
    change: "Change my answer",
    keep: "Keep it",
  },
  questions: {
    howMany: "How many of you?",
    children: "children",
    adults: "adults",
    names: "Who's coming?",
    namesHint: "First names are plenty. Everyone counts, little ones too.",
    dietary: "Anything we should know about food?",
    dietaryNote: "Allergies or anything else, in your words",
    access: "Any access needs?",
    accessHint: "Step-free entry, a quiet corner, anything that helps. Only if it helps us. Skip if not.",
    note: "A note for the host (optional)",
    emergencyName: "Emergency contact name",
    emergencyPhone: "Emergency contact mobile",
    send: "Send my reply",
    skip: "Skip the rest",
  },
  thanks: {
    yesTitle: "See you there!",
    yesBody: (count: number, host: string) =>
      count > 1 ? `We've got you down for ${count}. ${host} can't wait to see you.` : `We've got you down. ${host} can't wait to see you.`,
    noTitle: "Sorry you can't make it",
    noBody: (host: string) => `${host} will miss you. Thanks for letting us know.`,
    addToCalendar: "Add to calendar",
    google: "Google Calendar",
    apple: "Apple or Outlook",
    changed: "Reply updated",
  },
  sections: {
    details: "The details",
    day: "The day",
    afternoon: "The order of the afternoon",
    goodToKnow: "Good to know",
    plate: "Bring a plate",
    updates: "Updates",
    updatesBody: "Anything that changes shows here.",
    photos: "Photos",
    photosBody: "A photo for you after the party.",
    openInMaps: "Open in Maps",
    when: "When",
    where: "Where",
    wear: "Wear",
    questions: (host: string) => `Questions? Text ${host}`,
  },
  lines: {
    parentsStay: "Parents and family welcome to stay.",
    dropOff: "This is a drop-off party. We'll take good care of them.",
    siblingsWelcome: "Little brothers and sisters are welcome, just count them in your reply.",
    siblingsNo: "We're keeping it to invited kids only. Sorry, siblings!",
    giftsNone: "No gifts please, your company is the present.",
    giftsOptional: "Gifts are entirely optional.",
    photosKidsOff: "We'd love you to take photos, just please keep photos of the kids off social media. Thank you!",
    photosAsk: "Snap away, and please check with people before posting them online.",
    photosShare: "Take all the photos you like and share them with us after.",
    plateFree: "Bring something for the table if you feel inspired. No pressure at all.",
  },
  host: {
    previewReply: "Your guests answer here. This is your own preview, so nothing you tap is counted.",
    layoutHeading: "Layout",
    layoutHint: "Pick one to see it. Your guests see whatever is selected when you save.",
    openFull: "Open full size",
    sectionsHeading: "What the invite shows",
    sectionsHint: "A section with nothing in it stays hidden anyway. These are for leaving one out on purpose.",
    savedTitle: "Saved.",
    savedBody: "Your guests' links show the change straight away.",
    savedWithoutSections: "One thing did not save: the section switches need migration 0004 in the database first. Everything else is saved.",
    backToParty: "Back to the party",
    coming: "coming",
    saidYes: "said yes",
    saidNo: "said no",
    noReply: "no reply",
    opened: "opened, not replied",
    addGuest: "Add a guest",
    addOne: "One at a time",
    addMany: "Paste a list",
    pasteLabel: "One guest per line",
    pasteHint: "Name and mobile on the same line, in any order. Copy straight from a note or a spreadsheet. Add how many you expect with 2a 2k, or 2 adults 2 kids. Guests with no mobile still get a link you can share by hand.",
    pasteExample: "Priya Nair 0400 111 222 2a 2k\nThe Nguyens, 0400 222 333, 2 adults 3 kids\nSam from swimming 1a",
    addAll: "Add them all",
    pickContacts: "Pick from contacts",
    noContactsApi: "Your phone does not let a website read contacts. Paste a list instead, or type them in.",
    name: "Who the invite is for (the child, e.g. Oliver, or The Nairs)",
    contactName: "Whose phone you're texting (e.g. their mum, Priya)",
    phone: "Mobile",
    expected: "How many you expect (optional)",
    expectedHint: "Only a guess, so their reply is one tap. They can change it.",
    expectedChildren: "Children",
    expectedAdults: "Adults",
    expecting: (children: number | null, adults: number | null) => {
      const parts = [
        children ? `${children} ${children === 1 ? "child" : "children"}` : null,
        adults ? `${adults} ${adults === 1 ? "adult" : "adults"}` : null,
      ].filter(Boolean);
      return parts.length ? `expecting ${parts.join(" and ")}` : "";
    },
    add: "Add",
    text: "Text",
    textPick: "Text, pick in Messages",
    whatsapp: "WhatsApp",
    share: "Share",
    copy: "Copy link",
    copied: "Copied",
    sendNext: "Send next",
    allSent: "Everyone has been sent their link.",
    groupLink: "Group link for chats",
    groupLinkHint: "Anyone can open it. It asks their name, then gives them a personal link of their own.",
    remind: "Remind",
    newLink: "New link",
    trail: {
      added: "added",
      sent: "sent",
      opened: "opened",
      replied: "replied",
      reminded: "reminded",
    },
  },
  templates: {
    text: "Hi {name}! You're invited to {title}{date}. Everything is here, and you can reply with one tap: {link}",
    reminder: "Hi {name}, just checking you saw this one. {title}{date}. Can you make it? {link}",
    seeYouSoon: "See you tomorrow! {address}. Everything you need: {link}",
  },
  closed: {
    title: "This link is closed",
    body: "The host has closed the group link. Text them and they'll send you your own.",
  },
  notFound: {
    title: "That link doesn't look right",
    body: "Check the message it came in, or ask the host to send it again.",
  },
} as const;
